server:
  port: 8011

spring:
  thymeleaf:
    cache: false
    #    prefix: classpath:/templates
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  #  datasource:
  #    driver-class-name:
  #      url:
  #      username:
  #      password:

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql:
#  properties:
#    hibernate:
#      format_sql: true